theme: minima
title: Blackstone Fortress Guide
author: Dahyek Grekh
email: dahyeknomnom@dprecipice.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome, explorers. You are now viewing Dahyek Grekh's journal detailing his ventures into the unknown, ever-shifting corridors and chambers of the enigmatic Blackstone Fortress. 

# social links
twitter_username: dahyekgrekh69 # DO NOT include the @ character, or else the build will fail!
github_username: dahyekgrekh69  # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
